[package]
name = "rust_crypto_test"
version = "0.1.0"
authors = ["djadji <djadji.traore75@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
rustc-serialize = "0.3"
rand = "0.3"
criterion = "0.2"

[[bench]]
name = "crypto_benchmark"
harness = false
